import pandas as pd

df = pd.read_csv("diabetes.csv")

print(df.head())
print(df.head(10))
print(df.tail())
print(df.tail(7))
print(df['Age'].dtype)
print(df.dtypes)
print(df.columns)
print(df.axes)
print(df.ndim)
print(df.size)
print(df.shape)
print(df.values)
print(df.values)
print(df.describe())
print(df.max())
print(df.min())
print(df.groupby(['Age']).size())
print(df['BMI'].mean())
print(df['Insulin'].median())
print(df['Age'].std())
print(df.dropna())
print(df.groupby(['Age'])['Insulin'].mean())
print(df[['Age','BMI']])
print(df.iloc[1,2,3,4], [2,4,6]])
print(df.iloc[10:20, [2,4,6]])
print(df.iloc[10:20])
print(df.iloc[10:20, ['Age,BMI']])
print(df.isnull())
print(df.notnull())
print(df.fillna(2))
print(df[['Age','BMI']].agg(['min','mean','max']))
print(len(df))
print(df.nunique())